# Generated by Django 4.2.5 on 2023-09-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first', max_length=50)),
                ('lastName', models.CharField(default='last', max_length=30)),
                ('username', models.CharField(default='user', max_length=30)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
