# Generated by Django 4.2.5 on 2023-09-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja_app', '0003_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_image',
            field=models.ImageField(upload_to='media/pooja_app/images/collections/'),
        ),
    ]
