# Generated by Django 4.2.5 on 2023-09-15 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pooja_app', '0004_alter_collection_collection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('item_price', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='media/pooja_app/images/items/')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pooja_app.collection')),
            ],
        ),
    ]
