# Generated by Django 4.2.5 on 2023-09-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooja_app', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
